
<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
	        <label>Usuario: <?php echo $this->user['name'];?></label><br>
	        <label>Categoria: .....</label><br>
    	    <label id="points">Puntos: <?php echo $this->user['points'];?></label><br>   
            </div>
            <div class="panel-body">
        		<h3 class="panel-title">Prueba Metodos</h3>   
				<label>Agregar 10 Puntos Usuario</label><br>
				<button id="addPoints" class="btn btn-info btn-sm">Probar</button>
            </div>
        </div>
    </div>
    
    <div class="col-md-9">   
      <label>Lista de Logros por Categoria</label>
      <?php foreach($this->achievments as $achievement){?>
      <?php $statusL = 0; $class="panel panel-default";?>
      	<?php foreach($achievementsByUser as $achievementUser ){?>	
      			<?php if($achievementUser['Achievements_idAchive'] == $achievement ['id_achive']){$class ="panel panel-success";}?>
      	<?php } ?>
	      <div class="<?php echo $class ?>">
   		 	 <div class="panel-heading"><?php echo $achievement['name'].'   Puntos:'.$achievement['points'];?></div>
      	  	 <div class="panel-body">
      	  	 	<ul>
      	  		<?php foreach($achievement['tasks'] as $task){?>
      	  			<?php $status = 0;
      	  			foreach ($taskMadeByUser as $taskUser){
      	  			    if($taskUser['id'] == $task['id']){
      	  			       $status =1;
      	  			    }
      	  			}
      	  			?>
      	  			
      	  	 	   <?php if($status == 1){?>
	      	  	 	   <li>
						<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> 	      	  	 	   
						<label class="text-success taskCompleted">
							<?php echo $task['descriptiont'].    ' Puntos:' .$task['points'];?>
						</label>	      	  	 	   
					  </li>
      	  	 	   <?php }else{?> 
	      	  	 	   <li class="">
					   <span class=""></span> 	      	  	 	   
							<?php echo $task['descriptiont'].    ' Puntos:' .$task['points'];?>	   
							<button id="<?php echo $task['id_task']?>" class="btn btn-warning btn-sm cheatBtn"> Hacer trampa</button>
    	  	  	 	   </li>
      	  	 	   <?php }?>
      	  	 	   							<br>   	  	 	   
      	  	 	   
      	  	 	   <?php }?>      	  	 	   
	      	  	 </ul>      	  	 	   
      	  	 </div>
    	 </div> 
       <?php }?>
        
     </div>


</div>

<style>

ul{
  list-style:none;
}

</style>

<script>

var $basePath = "<?php echo $this->basePath();?>";



$(document).on("click", "#addPoints", function(){
	var $points = 10;
	$.ajax({
		type: 'POST',
		url: $basePath + '/gamification/gamification/addpoints',
		data: {id_user : '1',points : $points},
		dataType: 'json',
		success: function(response){
			alert("Se agregaron 10 Puntos, el usuario ahora tiene: "+response.data.points + 'puntos')
			$("#points").html('Puntos:'+response.data.points);
		},
		error: function(){ console.log("Fallo, intentalo otra vez"); }
	});	
})

$(document).on("click", ".cheatBtn", function(){
	alert("Tramposo");
	$id_task = $(this).attr("id");
	$btn = $(this);
	$.ajax({
		type: 'POST',
		url: $basePath + '/gamification/gamification/savehistorytask',
		data: {id_user : '1',id_task : $id_task},
		dataType: 'json',
		success: function(response){
			if(response.data.taskComplete == 1){
				$btn.parent().addClass('text-success taskCompleted');
				$btn.parent().find('span').addClass('glyphicon glyphicon-ok');
				$btn.remove();
				alert("Tarea Realizada, el usuario ahora tiene: "+response.data.updatedPoints + 'puntos')
				$("#points").html('Puntos:'+response.data.updatedPoints);				
			}
					},
		error: function(){ console.log("Fallo, intentalo otra vez"); }
	});	
})




</script>