<?php // echo "<pre>"; print_r($this->users); exit; ?>
<table class="table">
	<thead>
		<td>ID</td>
		<td>Nombre</td>
		<td>Apellido</td>
	</thead>
	<tbody>
		<!--Recorrer el arreglo-->
		<?php foreach ($this->users as $user) {?>
		<tr>
			<td><?php echo $user['id_users']; ?></td>
			<td><?php echo $user['name']; ?></td>
			<td><?php echo $user['lastname']; ?></td>
			<td><?php echo $user['email']; ?></td>
			<td><a class="btn btn-primary" href="<?php echo $this->basePath()."/user/update/".$user['id_users'];?>">Modificar</a></td>
			<td><a class="btn btn-warning" href="<?php echo $this->basePath()."/user/delete/".$user['id_users'];?>">Eliminar</a></td>
		</tr>
		<?php } ?>
	</tbody>
</table>

<a class="btn btn-warning" href='http://localhost/gamification/public/user/add'"<?php echo $this->basePath()."users/add"?>">Agregar usuario</a>