<script src="http://jqueryvalidation.org/files/dist/jquery.validate.min.js"></script>
<script src="<?php echo $this->basePath('/gamificationlive/jquery.formatCurrency-1.4.0/jquery.formatCurrency-1.4.0.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('/gamificationlive/jquery-loading-overlay-master/src/loadingoverlay.min.js'); ?>"></script>
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

 
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath("gamificationlive/materialize/css/materialize.min.css"); ?>"  media="screen,projection"/>

    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath("gamificationlive/css/style-pegalinas.css"); ?>" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath('/gamificationlive/sweetalert2/sweetalert2.min.css'); ?>" />
    <link href="<?php echo $this->basePath('/gamificationlive/validetta-1.0.1/dist/validetta.css'); ?>" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>

    <!--Import jQuery before materialize.js-->
    
    <script type="text/javascript" src="<?php echo $this->basePath("gamificationlive/jquery/jquery-2.2.4.min.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath("gamificationlive/materialize/js/materialize.min.js"); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/gamificationlive/sweetalert2/sweetalert2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/gamificationlive/validetta-1.0.1/dist/validetta.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('/gamificationlive/validetta-1.0.1/localization/validettaLang-es-ES.js'); ?>"></script>

<div class="row">
	<h4 class="grey-text" style="padding-left: 15px;">Ingresa los datos de la tarea.</h4>
</div>

<div class="row">
	<div class="col s6 m6 l6">
		<?php 
		$form = $this->form;
		$form->prepare();
		
		echo $this->form()->openTag($form); ?>

		<div class="input-field col s12 m12 l12">
			<label for="name">Nombre:</label>
			<?php echo $this->formElement($form->get('name')); ?>			
		</div>
		<div class="input-field col s12 m12 l12">
			<label for="badge">Insignia:</label>
			<?php echo $this->formElement($form->get('badge')); ?>			
		</div>
		<div class="input-field col s12 m12 l12">
			<label for="imgpath">Ruta:</label>
			<?php echo $this->formElement($form->get('imgpath')); ?>			
		</div>
		<div class="input-field col s12 m12 l12">
			<label for="points">Puntos:</label>
			<?php echo $this->formElement($form->get('points')); ?>			
		</div>
		<div class="input-field col s12 m12 l12">
			<label class="datepicker" for="maxDate">Fecha limite:</label>
			<?php echo $this->formElement($form->get('maxDate')); ?>
		</div>

		<div class="row" style="margin-top: 35px;">

			<div class="col s12 m12 l12">

				<div class="col s12 m6 l6">
					<button type="submit"  class="waves-effect waves-light btn-large teal col s12 m12 l12">Guardar</button>
					<?php //echo $this->formElement($form->get('submitbutton')); ?>
				</div>


				<div class="col s12 m6 l6">
					<a href="<?php echo $this->basePath()."/tasks" ?>" class="waves-effect waves-light btn-large red col s12 m12 l12">Cancelar</a>
				</div>

			</div>

		</div>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>

<script>
	$('.datepicker').pickadate({
		format: 'dd-mm-yyyy',
    	selectMonths: true, // Creates a dropdown to control month
    	selectYears: 15, // Creates a dropdown of 15 years to control year
		monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
		monthsShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
		weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
		weekdaysShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
		//showMonthsShort: true,
		today: 'Hoy',
		clear: 'Limpiar',
		close: 'Cerrar',
		max: true,
  	});  
</script>
