<?php // echo "<pre>"; print_r($this->tasks); exit; ?>
<table class="table">
	<thead>
		<td>ID</td>
		<td>Nombre</td>
		<td>Insignia</td>
		<td>Ruta</td>
		<td>Puntos</td>
		<td>Fecha limite</td>
	</thead>
	<tbody>
		<!--Recorrer el arreglo-->
		<?php foreach ($this->tasks as $tasks) {?>
		<tr>
			<td><?php echo $tasks['id']; ?></td>
				<td><?php echo $tasks['name']; ?></td>
				<td><?php echo $tasks['badge']; ?></td>
				<td><?php echo $tasks['imgpath']; ?></td>
				<td><?php echo $tasks['points']; ?></td>
				<td><?php echo $tasks['maxDate']; ?></td>
			<td><a class="btn btn-primary" href="<?php echo $this->basePath()."/tasks/update/".$tasks['id'];?>">Modificar</a></td>
			<td><a class="btn btn-warning" href="<?php echo $this->basePath()."/tasks/delete/".$tasks['id'];?>">Eliminar</a></td>
		</tr>
		<?php } ?>
	</tbody>
</table>


<a class="btn btn-warning" href='http://localhost/gamification/public/tasks/add'"<?php echo $this->basePath()."tasks/add"?>">Agregar usuario</a>