<div class="row">
	<div id= "form" class="col-md-8">
		<?php 
		$form = $this->form;
		$form->prepare();
		//abrir formulario
		echo $this->form()->openTag($form);
		//linea para obtener el campo
		echo $this->formElement($form->get('id'));

		echo $this->formlabel($form->get('name'));
		//linea para obtener el texto del campo
		echo $this->formElement($form->get('name'));

		echo $this->formlabel($form->get('Levels_idLvl'));
		echo $this->formElement($form->get('Levels_idLvl'));

		echo $this->formlabel($form->get('points'));
		echo $this->formElement($form->get('points'));

		echo $this->formElement($form->get('submit'));
		//cerrar formulario
		echo $this->form()->closeTag();
		?>
	</div>
</div>