<?php // echo "<pre>"; print_r($this->users); exit; ?>
<table class="table">
	<thead>
		<td>ID</td>
		<td>Username</td>
		<td>Nivel</td>
		<td>Puntos</td>
	</thead>
	<tbody>
		<!--Recorrer el arreglo-->
		<?php foreach ($this->users as $user) {?>
		<tr>
			<td><?php echo $user['id']; ?></td>
			<td><?php echo $user['name']; ?></td>
			<td><?php echo $user['Levels_idLvl']; ?></td>
			<td><?php echo $user['points']; ?></td>
			<td><a class="btn btn-primary" href="<?php echo $this->basePath()."/user/update/".$user['id'];?>">Modificar</a></td>
			<td><a class="btn btn-warning" href="<?php echo $this->basePath()."/user/delete/".$user['id'];?>">Eliminar</a></td>
		</tr>
		<?php } ?>
	</tbody>
</table>


<a class="btn btn-warning" href="<?php echo $this->basePath()."/user/add"?>">Agregar usuario</a>